package com.amendil.common.entities.`type`

enum CHAggregatedType(val name: String) extends CHType:
  case Any extends CHAggregatedType("Any")
  case AnyNonMapNonNullableNonLowCardinality extends CHAggregatedType("AnyNonMapNonNullableNonLowCardinality")
  case AnyNonNullableNonLowCardinality extends CHAggregatedType("AnyNonNullableNonLowCardinality")
  case Bitmap extends CHAggregatedType("Bitmap")
  case DateOrDateTime extends CHAggregatedType("DateOrDateTime")
  case Date32OrDateTime64 extends CHAggregatedType("Date32OrDateTime64")
  case DateLikeOrDateTime extends CHAggregatedType("DateLikeOrDateTime")
  case DateLikeOrDateTimeLike extends CHAggregatedType("DateLikeOrDateTimeLike")
  case DateLike extends CHAggregatedType("DateLike")
  case DateTimeLike extends CHAggregatedType("DateTimeLike")
  case DateTimeUnit extends CHAggregatedType("DateTimeUnit")
  case DateTime64Unit extends CHAggregatedType("DateTime64Unit")
  case Geo extends CHAggregatedType("Geo")
  case Interval extends CHAggregatedType("Interval")
  case IntervalDate extends CHAggregatedType("IntervalDate")
  case IntervalTime extends CHAggregatedType("IntervalTime")
  case IntervalTime64 extends CHAggregatedType("IntervalTime64")
  case IP extends CHAggregatedType("IP")
  case LowCardinality extends CHAggregatedType("LowCardinality")
  case LowCardinalityNullable extends CHAggregatedType("LowCardinalityNullable")
  case MapKey extends CHAggregatedType("MapKey")
  case Nullable extends CHAggregatedType("Nullable")
  case StringLike extends CHAggregatedType("StringLike")
  case TimeOrTime64Unit extends CHAggregatedType("TimeOrTime64Unit")

  // Numbers
  case DecimalLike extends CHAggregatedType("DecimalLike")
  case Float extends CHAggregatedType("Float")
  case Int extends CHAggregatedType("Int")
  case IntMax16Bits extends CHAggregatedType("IntMax16Bits")
  case IntMax32Bits extends CHAggregatedType("IntMax32Bits")
  case IntMax64Bits extends CHAggregatedType("IntMax64Bits")
  case IntMax128Bits extends CHAggregatedType("IntMax128Bits")
  case NonDecimal extends CHAggregatedType("NonDecimal")
  case NonDecimalMax32Bits extends CHAggregatedType("NonDecimalMax32Bits")
  case NonDecimalMax64Bits extends CHAggregatedType("NonDecimalMax64Bits")
  case NonDecimalNorFloat extends CHAggregatedType("NonDecimalNorFloat")
  case NonDecimalNorFloatMax8Bits extends CHAggregatedType("NonDecimalNorFloatMax8Bits")
  case NonDecimalNorFloatMax16Bits extends CHAggregatedType("NonDecimalNorFloatMax16Bits")
  case NonDecimalNorFloatMax32Bits extends CHAggregatedType("NonDecimalNorFloatMax32Bits")
  case NonDecimalNorFloatMax64Bits extends CHAggregatedType("NonDecimalNorFloatMax64Bits")
  case Number extends CHAggregatedType("Number")
  case NonFloat32Number extends CHAggregatedType("NonFloat32Number")
  case UInt extends CHAggregatedType("UInt")
  case UIntMax16Bits extends CHAggregatedType("UIntMax16Bits")
  case UIntMax32Bits extends CHAggregatedType("UIntMax32Bits")
  case UIntMax64Bits extends CHAggregatedType("UIntMax64Bits")
  case UIntMax128Bits extends CHAggregatedType("UIntMax128Bits")

  // LowCardinality(Numbers)
  case LowCardinalityFloat extends CHAggregatedType("LowCardinalityFloat")
  case LowCardinalityInt extends CHAggregatedType("LowCardinalityInt")
  case LowCardinalityIntMax64Bits extends CHAggregatedType("LowCardinalityIntMax64Bits")
  case LowCardinalityNonDecimal extends CHAggregatedType("LowCardinalityNonDecimal")
  case LowCardinalityNonDecimalMax64Bits extends CHAggregatedType("LowCardinalityNonDecimalMax64Bits")
  case LowCardinalityNonDecimalNorFloatMax64Bits extends CHAggregatedType("LowCardinalityNonDecimalNorFloatMax64Bits")
  case LowCardinalityUInt extends CHAggregatedType("LowCardinalityUInt")
  case LowCardinalityUIntMax64Bits extends CHAggregatedType("LowCardinalityUIntMax64Bits")

  // LowCardinality(Nullable(Numbers))
  case LowCardinalityNullableFloat extends CHAggregatedType("LowCardinalityNullableFloat")
  case LowCardinalityNullableInt extends CHAggregatedType("LowCardinalityNullableInt")
  case LowCardinalityNullableIntMax64Bits extends CHAggregatedType("LowCardinalityNullableIntMax64Bits")
  case LowCardinalityNullableNonDecimal extends CHAggregatedType("LowCardinalityNullableNonDecimal")
  case LowCardinalityNullableNonDecimalMax64Bits extends CHAggregatedType("LowCardinalityNullableNonDecimalMax64Bits")
  case LowCardinalityNullableNonDecimalNorFloatMax64Bits
      extends CHAggregatedType("LowCardinalityNullableNonDecimalNorFloatMax64Bits")
  case LowCardinalityNullableUInt extends CHAggregatedType("LowCardinalityNullableUInt")
  case LowCardinalityNullableUIntMax64Bits extends CHAggregatedType("LowCardinalityNullableUIntMax64Bits")

  // Nullable(Numbers)
  case NullableDecimalLike extends CHAggregatedType("NullableDecimalLike")
  case NullableFloat extends CHAggregatedType("NullableFloat")
  case NullableInt extends CHAggregatedType("NullableInt")
  case NullableIntMax64Bits extends CHAggregatedType("NullableIntMax64Bits")
  case NullableNonDecimal extends CHAggregatedType("NullableNonDecimal")
  case NullableNonDecimalMax64Bits extends CHAggregatedType("NullableNonDecimalMax64Bits")
  case NullableNonDecimalNorFloatMax64Bits extends CHAggregatedType("NullableNonDecimalNorFloatMax64Bits")
  case NullableNumber extends CHAggregatedType("NullableNumber")
  case NullableUInt extends CHAggregatedType("NullableUInt")
  case NullableUIntMax64Bits extends CHAggregatedType("NullableUIntMax64Bits")
