version: '3.8'
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:24.2.2.71-alpine'
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/config/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/config/z_no_logging.xml:/etc/clickhouse-server/config.d/z_no_logging.xml
      - ${PWD}/config/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/config/public_suffix_list.dat:/var/lib/clickhouse/top_level_domains/public_suffix_list.dat
      - ${PWD}/config/catboost.so:/etc/clickhouse-server/model/catboost.so
      - ${PWD}/config/titanic.catboost.bin:/etc/clickhouse-server/model/titanic.catboost.bin
      - ${PWD}/config/lemmatizer_en.bin:/var/lib/clickhouse/user_files/lemmatizer_en.bin
      - ${PWD}/config/synonym_en.txt:/var/lib/clickhouse/user_files/synonym_en.txt
      - ${PWD}/config/wordnet/adj.exc:/var/lib/clickhouse/user_files/wordnet/adj.exc
      - ${PWD}/config/wordnet/adv.exc:/var/lib/clickhouse/user_files/wordnet/adv.exc
      - ${PWD}/config/wordnet/cntlist:/var/lib/clickhouse/user_files/wordnet/cntlist
      - ${PWD}/config/wordnet/cntlist.rev:/var/lib/clickhouse/user_files/wordnet/cntlist.rev
      - ${PWD}/config/wordnet/cousin.exc:/var/lib/clickhouse/user_files/wordnet/cousin.exc
      - ${PWD}/config/wordnet/data.adj:/var/lib/clickhouse/user_files/wordnet/data.adj
      - ${PWD}/config/wordnet/data.adv:/var/lib/clickhouse/user_files/wordnet/data.adv
      - ${PWD}/config/wordnet/data.noun:/var/lib/clickhouse/user_files/wordnet/data.noun
      - ${PWD}/config/wordnet/data.verb:/var/lib/clickhouse/user_files/wordnet/data.verb
      - ${PWD}/config/wordnet/dbfiles/adj.all:/var/lib/clickhouse/user_files/wordnet/dbfiles/adj.all
      - ${PWD}/config/wordnet/dbfiles/adj.pert:/var/lib/clickhouse/user_files/wordnet/dbfiles/adj.pert
      - ${PWD}/config/wordnet/dbfiles/adj.ppl:/var/lib/clickhouse/user_files/wordnet/dbfiles/adj.ppl
      - ${PWD}/config/wordnet/dbfiles/adv.all:/var/lib/clickhouse/user_files/wordnet/dbfiles/adv.all
      - ${PWD}/config/wordnet/dbfiles/cntlist:/var/lib/clickhouse/user_files/wordnet/dbfiles/cntlist
      - ${PWD}/config/wordnet/dbfiles/noun.act:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.act
      - ${PWD}/config/wordnet/dbfiles/noun.animal:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.animal
      - ${PWD}/config/wordnet/dbfiles/noun.artifact:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.artifact
      - ${PWD}/config/wordnet/dbfiles/noun.attribute:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.attribute
      - ${PWD}/config/wordnet/dbfiles/noun.body:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.body
      - ${PWD}/config/wordnet/dbfiles/noun.cognition:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.cognition
      - ${PWD}/config/wordnet/dbfiles/noun.communication:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.communication
      - ${PWD}/config/wordnet/dbfiles/noun.event:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.event
      - ${PWD}/config/wordnet/dbfiles/noun.feeling:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.feeling
      - ${PWD}/config/wordnet/dbfiles/noun.food:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.food
      - ${PWD}/config/wordnet/dbfiles/noun.group:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.group
      - ${PWD}/config/wordnet/dbfiles/noun.location:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.location
      - ${PWD}/config/wordnet/dbfiles/noun.motive:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.motive
      - ${PWD}/config/wordnet/dbfiles/noun.object:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.object
      - ${PWD}/config/wordnet/dbfiles/noun.person:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.person
      - ${PWD}/config/wordnet/dbfiles/noun.phenomenon:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.phenomenon
      - ${PWD}/config/wordnet/dbfiles/noun.plant:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.plant
      - ${PWD}/config/wordnet/dbfiles/noun.possession:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.possession
      - ${PWD}/config/wordnet/dbfiles/noun.process:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.process
      - ${PWD}/config/wordnet/dbfiles/noun.quantity:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.quantity
      - ${PWD}/config/wordnet/dbfiles/noun.relation:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.relation
      - ${PWD}/config/wordnet/dbfiles/noun.shape:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.shape
      - ${PWD}/config/wordnet/dbfiles/noun.state:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.state
      - ${PWD}/config/wordnet/dbfiles/noun.substance:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.substance
      - ${PWD}/config/wordnet/dbfiles/noun.time:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.time
      - ${PWD}/config/wordnet/dbfiles/noun.Tops:/var/lib/clickhouse/user_files/wordnet/dbfiles/noun.Tops
      - ${PWD}/config/wordnet/dbfiles/verb.body:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.body
      - ${PWD}/config/wordnet/dbfiles/verb.change:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.change
      - ${PWD}/config/wordnet/dbfiles/verb.cognition:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.cognition
      - ${PWD}/config/wordnet/dbfiles/verb.communication:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.communication
      - ${PWD}/config/wordnet/dbfiles/verb.competition:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.competition
      - ${PWD}/config/wordnet/dbfiles/verb.consumption:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.consumption
      - ${PWD}/config/wordnet/dbfiles/verb.contact:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.contact
      - ${PWD}/config/wordnet/dbfiles/verb.creation:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.creation
      - ${PWD}/config/wordnet/dbfiles/verb.emotion:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.emotion
      - ${PWD}/config/wordnet/dbfiles/verb.Framestext:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.Framestext
      - ${PWD}/config/wordnet/dbfiles/verb.motion:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.motion
      - ${PWD}/config/wordnet/dbfiles/verb.perception:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.perception
      - ${PWD}/config/wordnet/dbfiles/verb.possession:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.possession
      - ${PWD}/config/wordnet/dbfiles/verb.social:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.social
      - ${PWD}/config/wordnet/dbfiles/verb.stative:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.stative
      - ${PWD}/config/wordnet/dbfiles/verb.weather:/var/lib/clickhouse/user_files/wordnet/dbfiles/verb.weather
      - ${PWD}/config/wordnet/index.adj:/var/lib/clickhouse/user_files/wordnet/index.adj
      - ${PWD}/config/wordnet/index.adv:/var/lib/clickhouse/user_files/wordnet/index.adv
      - ${PWD}/config/wordnet/index.noun:/var/lib/clickhouse/user_files/wordnet/index.noun
      - ${PWD}/config/wordnet/index.sense:/var/lib/clickhouse/user_files/wordnet/index.sense
      - ${PWD}/config/wordnet/index.verb:/var/lib/clickhouse/user_files/wordnet/index.verb
      - ${PWD}/config/wordnet/log.grind.3.1:/var/lib/clickhouse/user_files/wordnet/log.grind.3.1
      - ${PWD}/config/wordnet/noun.exc:/var/lib/clickhouse/user_files/wordnet/noun.exc
      - ${PWD}/config/wordnet/sentidx.vrb:/var/lib/clickhouse/user_files/wordnet/sentidx.vrb
      - ${PWD}/config/wordnet/sents.vrb:/var/lib/clickhouse/user_files/wordnet/sents.vrb
      - ${PWD}/config/wordnet/verb.exc:/var/lib/clickhouse/user_files/wordnet/verb.exc
      - ${PWD}/config/wordnet/verb.Framestext:/var/lib/clickhouse/user_files/wordnet/verb.Framestext
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'